package by.htp3.hotel.controller;

public enum CommandName {
	LOGINATION, REGISTRATION, SHOW_FREE_ROOMS,

	CHANGE_LANGUAGE, ADD_NEW_ROOM, ADD_NEW_ROOM_FORM, GIVE_FEEDBACK, SHOW_NEWS, BOOK_ROOM, PAYMENT, SEARCH_FOR_ROOM, LOGOUT, SHOW_USERS, GO_TO_MAIN, GO_TO_PAYMENT, GIVE_FEEDBACK_FORM, BOOK_ROOM_FORM, GO_TO_LOGIN, BLOCK_USER, BLOCK_USER_FORM
}
